/** @format */

import type { Metadata } from "next";
import "./globals.css";
import NavbarDesktop from "@/components/navbar/navbar.desktop";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
  title: "KFC Chicken Indonesia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
<<<<<<< Updated upstream
        <NavbarDesktop />
        {children}
        <Footer />
=======
        <SessionProvider>
          <NavbarDesktop />
          {children}
          <Footer />
          <Toaster />
        </SessionProvider>
>>>>>>> Stashed changes
      </body>
    </html>
  );
}
